"""Criação de tabelas

Revision ID: 0ef875ed8c25
Revises: 5debf75b7afe
Create Date: 2022-09-20 12:32:32.941739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef875ed8c25'
down_revision = '5debf75b7afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_cars', sa.Column('daily_fix_km', sa.Integer(), nullable=False))
    op.drop_column('tb_cars', 'daily_fixe_km')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_cars', sa.Column('daily_fixe_km', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tb_cars', 'daily_fix_km')
    # ### end Alembic commands ###
