"""Criação de tabelas

Revision ID: 0ff12a7259ec
Revises: 0ef875ed8c25
Create Date: 2022-09-20 13:08:37.073087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff12a7259ec'
down_revision = '0ef875ed8c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_cars', 'maintenance_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_cars', 'maintenance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
