"""Criação de tabelas

Revision ID: 5debf75b7afe
Revises: be69bc01c3d1
Create Date: 2022-09-20 12:28:43.642933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5debf75b7afe'
down_revision = 'be69bc01c3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_cars', sa.Column('car_color', sa.String(), nullable=False))
    op.drop_column('tb_cars', 'car_collor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_cars', sa.Column('car_collor', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tb_cars', 'car_color')
    # ### end Alembic commands ###
